### ISSUE TITLE
[버그리포트] Mybatis 연동중 Mybatis-config 연결 오류 발생

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/wms-justdo#28]
# 발생 일시
2024-05-17
# 발생 위치
- sellerMenu -> notification menu
# 증상
Sql 문법 에러 및 mybatis 경로 오류
# 재현 방법
mybatistemplete 클래스의 경로 수정 및 전체 xml 경로 수정, xml파일 내의 sql 문법수정
# 스크린샷
<img width="601" alt="image" src="https://github.com/ssg-240304-java2/wms-justdo/assets/162261441/4cb253ee-0301-4afc-b254-4d7133293c28">

**Comment by lucinda96** [comment]
Mybatis 연동과관련된 내용 wiki에 작성했습니다.
아래의 링크에서 확인해주세요
https://github.com/ssg-240304-java2/wms-justdo/wiki/Mybatis%EC%97%B0%EB%8F%99
