### ISSUE TITLE
[버그리포트] 이전메뉴 선택시 입력을 무한으로 요청하는 오류발생

### ISSUE THREAD

**Issue by finite2030** [ssg-240304-java2/wms-justdo#31]
# 발생 일시
2024-05-18
# 발생 위치
시스템 관리자 메뉴 -> 회원 관리 메뉴에서 이전 메뉴로 돌아갈 때
switch문의 case 9번 이전 화면으로 이동, inputReader를 종료하려고 ir.close() 할 경우 "입력 오류가 발생했습니다" 라는 메시지 무한 출력
# 증상
입력을 무한히 받는 현상이 있음
# 재현 방법 
서브 메뉴에서  이전 화면으로 이동할 경우, inputReader 객체 제거 시 발생
# 스크린샷
![image](https://github.com/ssg-240304-java2/wms-justdo/assets/162261458/b5ea92fc-ede4-482a-a675-96fabd817aab)

**Comment by lucinda96** [comment]
ir을 어떻게 선언하셨는지 확인 안 되어 정확한 원인을 파악이 어렵습니다.
다만 코드에서는 동일한 문제가 발생하고있지않아서 ir의 선언 문제인것같습니다.
아래와 같이 선언되어있는지 확인부탁드립니다.

private InputReader ir= InputReaderFactory.getInputReader();
