### ISSUE TITLE
[버그리포트] order테이블명 수정 요청

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/wms-justdo#32]
# 발생 일시
2024-05-18
# 발생 위치
Mapper.java>insert order메소드

# 증상
order 테이블 예약어랑 곂침 문제
# 재현 방법
order 테이블명 변경
ex) order_product
# 스크린샷
- 테이블 이미지
<img width="514" alt="image" src="https://github.com/ssg-240304-java2/wms-justdo/assets/162261441/efe0abec-8fdf-4684-b0ce-449c7d7d7a7f">

<br>
- 오류내용
<img width="904" alt="image" src="https://github.com/ssg-240304-java2/wms-justdo/assets/162261441/bb01edef-4b4b-4044-b95d-bb4e2944aa94">

**Comment by lucinda96** [comment]
참고했던 배달의 민족erd 및 주문테이블명 검색 시
주문테이블명을 orders로 사용중이서 orders로 변경했습니다.

- 배달의민족 erd의 주문테이블
<img width="343" alt="image" src="https://github.com/ssg-240304-java2/wms-justdo/assets/90363122/0af07f86-6207-4bd4-a937-4654e7053959">
<br>
- 변경된 테이블명
<img width="426" alt="image" src="https://github.com/ssg-240304-java2/wms-justdo/assets/90363122/8c016264-38b8-4158-b30c-baa936cf03f9">
